CREATE TABLE IF NOT EXISTS participants (
  id SERIAL PRIMARY KEY,
  participant_code VARCHAR(32) UNIQUE NOT NULL,
  name VARCHAR(120) NOT NULL,
  phone VARCHAR(32) UNIQUE NOT NULL,
  address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS nights (
  id SERIAL PRIMARY KEY,
  participant_id INTEGER NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  night_number INTEGER NOT NULL CHECK (night_number BETWEEN 21 AND 30),
  date DATE NOT NULL,
  sahur BOOLEAN DEFAULT FALSE,
  iftar BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS children (
  id SERIAL PRIMARY KEY,
  participant_id INTEGER NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  name VARCHAR(120) NOT NULL,
  age INTEGER CHECK (age >= 0)
);

CREATE TABLE IF NOT EXISTS attendance (
  id SERIAL PRIMARY KEY,
  participant_id INTEGER NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  night_number INTEGER NOT NULL CHECK (night_number BETWEEN 21 AND 30),
  sahur_attended BOOLEAN DEFAULT FALSE,
  iftar_attended BOOLEAN DEFAULT FALSE,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
